### ISSUE TITLE
frames changing when using arrow keys in the interaction settings

### ISSUE THREAD

**Issue by RokasEl** [zincware/ZnDraw#109]
If an interaction has a `str` field, and one tries to use arrow keys to change the cursor position in this field, the current displayed frame changes as well.
Ideally, when one is typing in the interaction menu, the frame should not be changing.

**Comment by PythonFZ** [comment]
fixed in [0e6ef90](https://github.com/zincware/ZnDraw/pull/140/commits/0e6ef9043587dd098a069120f3c1d0149277a6bd) with `pip install pip install zndraw==0.2.0a14`
