### ISSUE TITLE
`zndraw` without file path

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnDraw#133]
Just modify  https://github.com/zincware/ZnDraw/blob/6a7695b41a8421a6735d384f026ff5732da9415c/zndraw/shared.py#L168-L175 to create an empty ase.Atoms  object

- [ ] still allow adding a canvas

**Comment by RokasEl** [comment]
also, when you already loaded an xyz, moving to a clean state would be useful. Could this be done with a ctrl+A and a delete?

Or maybe a separate button as well.

**Comment by PythonFZ** [comment]
fixed in [0e6ef90](https://github.com/zincware/ZnDraw/pull/140/commits/0e6ef9043587dd098a069120f3c1d0149277a6bd) with `pip install pip install zndraw==0.2.0a14`
