### ISSUE TITLE
bad interactions between atom selection and bond display

### ISSUE THREAD

**Issue by bernstei** [zincware/ZnDraw#144]
1. With Scene / Bonds unchecked, select an atom with the GUI (right click).  Checking "Bonds" make the atom appear unselected (no highlight).   Unchecking bonds brings back the highlight.

2. If all atoms are unselected and bonds are displayed, selecting an atom highlights it and the connected half bond. Unchecking bonds hides the bond and leaves the atom highlighted.  Checking Bonds again turns off the selected atom highlight (and half bond isn't highlighted either).  Unchecking bonds again highlights the atom again.

**Comment by PythonFZ** [comment]
This issue was actually related to the `Simulation Box` being selected. There was an issue that prohibited updated which should be fixed in [bae3106](https://github.com/zincware/ZnDraw/pull/140/commits/bae3106a8373456e3647c73cc92ba9f092fb5e82)
