### ISSUE TITLE
atom index labels not hidden by closer atoms

### ISSUE THREAD

**Issue by bernstei** [zincware/ZnDraw#146]
index labels from atoms behind other atoms are still displayed (see 0, 5, 6 in attached image)

<img width="305" alt="Screen Shot 2023-08-29 at 11 25 24 AM" src="https://github.com/zincware/ZnDraw/assets/1202357/c19e4229-55bf-433a-a0a6-47172689c40d">

**Comment by PythonFZ** [comment]
I've tried multiple versions
#### 1
![image](https://github.com/zincware/ZnDraw/assets/46721498/1ef5809e-0371-434d-9737-5bde53b6faab)
#### 2
![image](https://github.com/zincware/ZnDraw/assets/46721498/a5a69eb2-fb1a-4c9b-ad02-65c82f9b8892)
#### 3 
![image](https://github.com/zincware/ZnDraw/assets/46721498/89f0189e-9556-4a33-9c81-74f39f5ad776)

But for large structures I wasn't able to get good looking results. Which one do you prefer and do you have an idea on how to improve this for large structures?

![image](https://github.com/zincware/ZnDraw/assets/46721498/4ee8319c-2186-4538-9663-49decca1fd34)

**Comment by bernstei** [comment]
I prefer 3 to 1. 

I don't love the number color in 2 - I think whatever contrasts best with the background (black in this case) is better.

I like being able to set an arbitrary offset between the atom center and the number (sometimes 1 is better than 2, sometimes the other way).

I think it's kind of a lost cause for structures as large as that.

**Comment by PythonFZ** [comment]
[28a7cd6](https://github.com/zincware/ZnDraw/pull/140/commits/28a7cd675f5e62146c753d5265e4b99edb353194) adds an option `Label Offset` to the scene menu. This should be fixed (closing on the next release)
![image](https://github.com/zincware/ZnDraw/assets/46721498/bfdd7c55-9478-4116-a9cf-2fdbf170d6f9)
![image](https://github.com/zincware/ZnDraw/assets/46721498/2b2bba32-26e3-4801-a526-9711d3817f9b)
![image](https://github.com/zincware/ZnDraw/assets/46721498/a6342dcb-bd37-44a0-b858-0482ba54181c)

**Comment by PythonFZ** [comment]
fixed in [0e6ef90](https://github.com/zincware/ZnDraw/pull/140/commits/0e6ef9043587dd098a069120f3c1d0149277a6bd) with `pip install pip install zndraw==0.2.0a14`
