### ISSUE TITLE
update `UpdateScene` base class

### ISSUE THREAD

**Issue by RokasEl** [zincware/ZnDraw#252]
Currently the base class is:

```
class UpdateScene(BaseModel, abc.ABC):
    model_config = ConfigDict(json_schema_extra=hide_method)

    @abc.abstractmethod
    def run(self, atom_ids: list[int], atoms: ase.Atoms, **kwargs) -> list[ase.Atoms]:
        pass
```

But the recent updates of modifiers pass the `ZnDraw` class to run instead and return `None`.

**Comment by PythonFZ** [comment]
This will be fixed in https://github.com/zincware/ZnDraw/tree/register_modifier 
There are still some things I need to fix before I can merge it, but the change you are looking for is implemented there.
