### ISSUE TITLE
Error while starting zndraw

### ISSUE THREAD

**Issue by gelzinyte** [zincware/ZnDraw#372]
Hi! I would like to give ZnDraw a try, however just trying to start it with `zndraw` throws an `AttributeError: module 'ssl' has no attribute 'wrap_socket'` error. Any ideas? I'm attaching a file with the full trace. 

[zndraw.err.txt](https://github.com/zincware/ZnDraw/files/14062733/zndraw.err.txt)

**Comment by PythonFZ** [comment]
Can you try `pip install --upgrade eventlet` and let me know if this fixes it? See https://github.com/eventlet/eventlet/issues/795

**Comment by gelzinyte** [comment]
Thanks, this seems to fix the issue!

P.S. zndraw seems to be restricting eventlet version to 0.33, whereas the upgrade force-installed 0.35. Superficially, zndraw seems to be ok with that, so updating the zndraw package requirements might solve this issue for the future?
