### ISSUE TITLE
Jupyer Widget

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnDraw#506]
- [x] token is not correct in `_repr_html_`
- [ ] can not copy/ paste out of widget
- [ ] dark mode from jupyer style

**Comment by PythonFZ** [comment]
@phohenberger  can this be closed?

**Comment by phohenberger** [comment]
The token should be fixed and copying inside the widget also works for me. Getting the dark mode from jupyter style did not really work for me, however on a different system, where the system theme was dark, `zndraw` switched to dark mode.

I think this is fine as it is. We can close this issue if thats ok for you
